version: "3"

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    volumes:
      - "sailredis:/data"
    networks:
      - sail

  pgsql:
    image: "postgres:13"
    container_name: pgsql
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${PG_PASSWORD:-secret}"
      POSTGRES_DB: "${PG_DB_NAME:-default}"
      POSTGRES_USER: "${PG_USER?:err}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-secret}"
    volumes:
      - "sailpgsql:/var/lib/postgresql/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${PG_DB_NAME:-default}", "-U", "${PG_USER}"]
      retries: 3
      timeout: 5s

  minio:
    image: "minio/minio:latest"
    container_name: "minio"
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-8900}:8900"
    environment:
      MINIO_ROOT_USER: "sail"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - "sailminio:/data/minio"
    networks:
      - sail
    command: minio server /data/minio --console-address ":8900"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s

  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: "mailhog"
    ports:
      - "${MAILHOG_PORT:-1025}:1025"
      - "${MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sailredis:
  sailpgsql:
  sailminio:
